"""
PDF Report Generation Service
Generates professional inspection reports with branding, images, structured data, and AI analysis.
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.platypus.flowables import HRFlowable, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional
import io

# Ensure you have your settings imported properly based on your project structure
from app.config import settings

class ReportService:
    """Service for generating PDF inspection reports"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f1f1f'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.HexColor('#6b7280'),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
        
        # Section header
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1f1f1f'),
            spaceAfter=12,
            spaceBefore=20,
            fontName='Helvetica-Bold',
            borderWidth=0,
            borderColor=colors.HexColor('#e5e7eb'),
            borderPadding=5
        ))
        
        # Info text
        self.styles.add(ParagraphStyle(
            name='InfoText',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#374151'),
            spaceAfter=6,
            fontName='Helvetica'
        ))
        
        # Footer style
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.HexColor('#9ca3af'),
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))

        # Centered footer for the end of the report (Fix for KeyError)
        self.styles.add(ParagraphStyle(
            name='CenteredFooter',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#6b7280'),
            alignment=TA_CENTER,
            fontName='Helvetica-Oblique',
            spaceBefore=20
        ))
    
    def _add_header(self, elements: List, logo_path: Optional[Path] = None):
        """Add professional header with logo and company info"""
        # Logo
        if logo_path and logo_path.exists():
            try:
                logo = Image(str(logo_path), width=1.5*inch, height=1.5*inch, kind='proportional')
                logo.hAlign = 'CENTER'
                elements.append(logo)
                elements.append(Spacer(1, 0.2*inch))
            except Exception as e:
                print(f"Could not load logo: {e}")
        
        # Company name
        company_name = Paragraph("MCS Robotics", self.styles['CustomTitle'])
        elements.append(company_name)
        
        # System name
        system_name = Paragraph("Container Inspection System", self.styles['CustomSubtitle'])
        elements.append(system_name)
        
        # Horizontal line
        elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#e5e7eb')))
        elements.append(Spacer(1, 0.3*inch))
    
    def _add_footer(self, canvas, doc):
        """Add footer to each page"""
        canvas.saveState()
        
        # Footer text
        footer_text = f"Generated by Container Inspection System v{getattr(settings, 'APP_VERSION', '3.0.0')} | MCS Robotics"
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#9ca3af'))
        canvas.drawCentredString(letter[0]/2, 0.5*inch, footer_text)
        
        # Page number
        page_num = f"Page {doc.page}"
        canvas.drawRightString(letter[0] - 0.75*inch, 0.5*inch, page_num)
        
        # Generation timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        canvas.drawString(0.75*inch, 0.5*inch, f"Generated: {timestamp}")
        
        canvas.restoreState()
    
    def generate_inspection_report(
        self,
        inspection_data: Dict,
        output_path: Optional[Path] = None
    ) -> bytes:
        """
        Generate a professional PDF report for an inspection
        
        Args:
            inspection_data: Dictionary containing inspection details
            output_path: Optional path to save PDF file
            
        Returns:
            PDF content as bytes
        """
        print(f"📄 Generating PDF report for inspection {inspection_data.get('id')}")
        print(f"   Container: {inspection_data.get('container_id')}")
        print(f"   Frames: {len(inspection_data.get('frames', []))}")
        
        # Log frame image paths
        for idx, frame in enumerate(inspection_data.get('frames', []), 1):
            img_path = frame.get('overlay_path') or frame.get('image_path')
            print(f"   Frame {idx}: {img_path}")
        
        # Create PDF buffer
        buffer = io.BytesIO()
        
        # Create document
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=1*inch,
            bottomMargin=1*inch
        )
        
        # Container for elements
        elements = []
        
        # Add header
        logo_path = getattr(settings, 'ROOT_DIR', Path('.')) / "frontend" / "assets" / "images" / "pti-logo.png"
        self._add_header(elements, logo_path)
        
        # Report title
        title = Paragraph("INSPECTION REPORT", self.styles['CustomTitle'])
        elements.append(title)
        elements.append(Spacer(1, 0.2*inch))
        
        # Report metadata
        report_date = datetime.now().strftime("%B %d, %Y at %H:%M:%S")
        metadata = Paragraph(f"<b>Report Generated:</b> {report_date}", self.styles['InfoText'])
        elements.append(metadata)
        elements.append(Spacer(1, 0.3*inch))
        
        # Inspection summary section
        elements.append(Paragraph("INSPECTION SUMMARY", self.styles['SectionHeader']))
        
        summary_data = [
            ['Inspection ID:', str(inspection_data.get('id', 'N/A'))],
            ['Container ID:', inspection_data.get('container_id', 'UNKNOWN')],
            ['ISO Type:', inspection_data.get('iso_type', 'Unknown')],
            ['Inspection Date:', inspection_data.get('timestamp', 'N/A')],
            ['Stage:', inspection_data.get('stage', 'None') or 'None'],
            ['Status:', inspection_data.get('status', 'N/A').upper()],
        ]
        
        summary_table = Table(summary_data, colWidths=[2*inch, 4*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#1f1f1f')),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 0.3*inch))
        
        # Risk assessment section
        elements.append(Paragraph("RISK ASSESSMENT", self.styles['SectionHeader']))
        
        risk_data = [
            ['Risk Score:', str(inspection_data.get('risk_score', 0))],
            ['Contamination Index:', f"{inspection_data.get('contamination_index', 1)}/9 ({inspection_data.get('contamination_label', 'Low')})"],
            ['People Nearby:', 'Yes' if inspection_data.get('people_nearby') else 'No'],
            ['Door Status:', inspection_data.get('door_status', 'Unknown') or 'Unknown'],
            ['Anomalies Present:', 'Yes' if inspection_data.get('anomalies_present') else 'No'],
        ]
        
        risk_table = Table(risk_data, colWidths=[2*inch, 4*inch])
        risk_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#1f1f1f')),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
        ]))
        elements.append(risk_table)
        elements.append(Spacer(1, 0.3*inch))
        
        # Scene analysis (if available)
        if inspection_data.get('scene_caption'):
            elements.append(Paragraph("SCENE ANALYSIS", self.styles['SectionHeader']))
            caption = Paragraph(inspection_data['scene_caption'], self.styles['InfoText'])
            elements.append(caption)
            elements.append(Spacer(1, 0.2*inch))
        
        if inspection_data.get('anomaly_summary'):
            elements.append(Paragraph("ANOMALY SUMMARY", self.styles['SectionHeader']))
            summary = Paragraph(inspection_data['anomaly_summary'], self.styles['InfoText'])
            elements.append(summary)
            elements.append(Spacer(1, 0.2*inch))
        
        # Frames and detections
        frames = inspection_data.get('frames', [])
        if frames:
            elements.append(PageBreak())
            elements.append(Paragraph("DETAILED ANALYSIS", self.styles['SectionHeader']))
            elements.append(Spacer(1, 0.2*inch))
            
            for idx, frame in enumerate(frames, 1):
                # Frame header
                frame_title = Paragraph(f"<b>Frame #{frame.get('id', idx)}</b>", self.styles['InfoText'])
                elements.append(frame_title)
                
                # Frame image (if available)
                image_path = frame.get('overlay_path') or frame.get('image_path')
                if image_path:
                    # Try multiple path resolutions
                    possible_paths = [
                        getattr(settings, 'STORAGE_ROOT', Path('.')).parent / image_path,
                        getattr(settings, 'ROOT_DIR', Path('.')) / image_path,
                        Path(image_path),
                    ]
                    
                    full_image_path = None
                    for path in possible_paths:
                        if path.exists():
                            full_image_path = path
                            break
                    
                    if full_image_path and full_image_path.exists():
                        try:
                            print(f"📸 Adding image to PDF: {full_image_path}")
                            img = Image(str(full_image_path), width=5*inch, height=3.75*inch, kind='proportional')
                            elements.append(img)
                            elements.append(Spacer(1, 0.1*inch))
                        except Exception as e:
                            print(f"❌ Could not load frame image {full_image_path}: {e}")
                            error_text = Paragraph(
                                f"<i>[Image not available: {image_path}]</i>", 
                                self.styles['InfoText']
                            )
                            elements.append(error_text)
                            elements.append(Spacer(1, 0.1*inch))
                    else:
                        print(f"⚠️  Image not found: {image_path}")
                        error_text = Paragraph(
                            f"<i>[Image not found: {image_path}]</i>", 
                            self.styles['InfoText']
                        )
                        elements.append(error_text)
                        elements.append(Spacer(1, 0.1*inch))
                
                # Frame info
                frame_info = [
                    ['Status:', frame.get('status', 'N/A').upper()],
                    ['Contamination:', f"{frame.get('contamination_index', 1)}/9"],
                    ['Detections:', str(len(frame.get('detections', [])))],
                ]
                
                frame_table = Table(frame_info, colWidths=[1.5*inch, 3.5*inch])
                frame_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f9fafb')),
                    ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#374151')),
                    ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
                ]))
                elements.append(frame_table)
                
                # Detections list
                detections = frame.get('detections', [])
                if detections:
                    elements.append(Spacer(1, 0.1*inch))
                    det_title = Paragraph("<b>Detected Objects:</b>", self.styles['InfoText'])
                    elements.append(det_title)
                    
                    det_data = [['#', 'Label', 'Category', 'Confidence']]
                    for det_idx, det in enumerate(detections, 1):
                        conf = f"{det.get('confidence', 0)*100:.1f}%" if det.get('confidence') else 'N/A'
                        det_data.append([
                            str(det_idx),
                            det.get('label', 'Unknown'),
                            det.get('category', 'N/A'),
                            conf
                        ])
                    
                    det_table = Table(det_data, colWidths=[0.5*inch, 2*inch, 1.5*inch, 1*inch])
                    det_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f1f1f')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, 0), 9),
                        ('FONTSIZE', (0, 1), (-1, -1), 8),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                        ('TOPPADDING', (0, 0), (-1, -1), 6),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
                    ]))
                    elements.append(det_table)
                
                elements.append(Spacer(1, 0.3*inch))
                
                # Page break after every 2 frames
                if idx % 2 == 0 and idx < len(frames):
                    elements.append(PageBreak())

        # =========================================================================
        # --- NEW EXTENSION: DEEP AI ANALYSIS SECTION ---
        # =========================================================================
        
        # Start the Deep Intelligence Annex on a new page
        elements.append(PageBreak())
        
        elements.append(Paragraph("DEEP AI INTELLIGENCE ANALYSIS", self.styles['SectionHeader']))
        elements.append(Spacer(1, 0.1*inch))
        
        # Extract the deep AI analysis narrative from data, or provide fallback
        ai_narrative = inspection_data.get('ai_narrative', 
            "The computer vision model identified general nominal conditions. "
            "No critical anomalies exceeding ISO 1496-1 limits were detected in this pass. "
            "Proceed with standard preventative maintenance."
        )
        
        elements.append(Paragraph("<b>Structural & Anomaly Narrative:</b>", self.styles['InfoText']))
        elements.append(Paragraph(ai_narrative, self.styles['Normal']))
        elements.append(Spacer(1, 0.3*inch))

        # Predictive Maintenance Forecast Table
        elements.append(Paragraph("<b>Predictive Maintenance Forecast:</b>", self.styles['InfoText']))
        elements.append(Spacer(1, 0.1*inch))
        
        # Extract predictive table data from inspection_data, or provide a default fallback
        pred_data = inspection_data.get('maintenance_forecast', [
            ["Component", "Detected Wear Level", "Recommended Action", "Timeline"],
            ["Corner Posts", "Low", "Routine Monitor", "12 Months"],
            ["Door Gaskets", "Nominal", "Clean/Lubricate", "6 Months"],
            ["Floor Planks", "Low", "Standard Sweep", "Ongoing"]
        ])
        
        pred_table = Table(pred_data, colWidths=[2*inch, 1.5*inch, 2*inch, 1.5*inch])
        pred_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f1f1f')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
        ]))
        elements.append(pred_table)
        elements.append(Spacer(1, 0.4*inch))
        
        # Final closing text
        elements.append(Paragraph("End of Automated Vision & AI Intelligence Report", self.styles['CenteredFooter']))
        
        # =========================================================================
        
        # Build PDF
        doc.build(elements, onFirstPage=self._add_footer, onLaterPages=self._add_footer)
        
        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        # Save to file if path provided
        if output_path:
            output_path.write_bytes(pdf_bytes)
        
        return pdf_bytes