"""
PDF Report Generation Service
Generates professional inspection reports with branding, images, and structured data.
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.platypus.flowables import HRFlowable, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional
import io

# Ensure your settings are imported properly based on your project structure
from app.config import settings

class ReportService:
    """Service for generating technical container inspection reports"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f1f1f'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.HexColor('#6b7280'),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1f1f1f'),
            spaceAfter=12,
            spaceBefore=20,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='InfoText',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#374151'),
            spaceAfter=6,
            fontName='Helvetica'
        ))

        self.styles.add(ParagraphStyle(
            name='TableNote',
            parent=self.styles['Italic'],
            fontSize=9,
            textColor=colors.HexColor('#4b5563'),
            leftIndent=10,
            rightIndent=10,
            spaceBefore=4,
            spaceAfter=12
        ))

        self.styles.add(ParagraphStyle(
            name='CenteredFooter',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#6b7280'),
            alignment=TA_CENTER,
            fontName='Helvetica-Oblique',
            spaceBefore=30
        ))
    
    def _add_header(self, elements: List, logo_path: Optional[Path] = None):
        if logo_path and logo_path.exists():
            try:
                logo = Image(str(logo_path), width=1.5*inch, height=1.5*inch, kind='proportional')
                logo.hAlign = 'CENTER'
                elements.append(logo)
                elements.append(Spacer(1, 0.2*inch))
            except Exception: pass
        
        elements.append(Paragraph("MCS Robotics", self.styles['CustomTitle']))
        elements.append(Paragraph("Container Inspection System", self.styles['CustomSubtitle']))
        elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#e5e7eb')))
        elements.append(Spacer(1, 0.3*inch))
    
    def _add_footer(self, canvas, doc):
        canvas.saveState()
        footer_text = f"Generated by MCS Robotics Inspection Suite v{getattr(settings, 'APP_VERSION', '3.0.0')}"
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#9ca3af'))
        canvas.drawCentredString(letter[0]/2, 0.5*inch, footer_text)
        canvas.drawRightString(letter[0] - 0.75*inch, 0.5*inch, f"Page {doc.page}")
        canvas.drawString(0.75*inch, 0.5*inch, f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        canvas.restoreState()
    
    def generate_inspection_report(self, inspection_data: Dict, output_path: Optional[Path] = None) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.75*inch, leftMargin=0.75*inch, topMargin=1*inch, bottomMargin=1*inch)
        elements = []
        
        logo_path = getattr(settings, 'ROOT_DIR', Path('.')) / "frontend" / "assets" / "images" / "pti-logo.png"
        self._add_header(elements, logo_path)
        
        elements.append(Paragraph("INSPECTION REPORT", self.styles['CustomTitle']))
        elements.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%B %d, %Y')}", self.styles['InfoText']))
        elements.append(Spacer(1, 0.3*inch))
        
        # --- SECTION 1: INSPECTION SUMMARY ---
        elements.append(Paragraph("INSPECTION SUMMARY", self.styles['SectionHeader']))
        summary_data = [
            ['Inspection ID:', str(inspection_data.get('id', 'N/A'))],
            ['Container ID:', inspection_data.get('container_id', 'UNKNOWN')],
            ['ISO Type:', inspection_data.get('iso_type', 'Unknown')],
            ['Stage:', inspection_data.get('stage', 'None')],
            ['Operational Status:', inspection_data.get('status', 'N/A').upper()],
        ]
        summary_table = Table(summary_data, colWidths=[2*inch, 4*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(summary_table)
        elements.append(Paragraph("<b>Table Context:</b> This section details administrative metadata and current logistics staging. Operational status indicates the container's readiness for transit based on structural visual confirmation.", self.styles['TableNote']))
        elements.append(Spacer(1, 0.2*inch))
        
        # --- SECTION 2: RISK ASSESSMENT ---
        elements.append(Paragraph("RISK ASSESSMENT", self.styles['SectionHeader']))
        risk_data = [
            ['Risk Score:', str(inspection_data.get('risk_score', 0))],
            ['Contamination Index:', f"{inspection_data.get('contamination_index', 1)}/9"],
            ['Safety Anomalies:', 'Yes' if inspection_data.get('anomalies_present') else 'No'],
        ]
        risk_table = Table(risk_data, colWidths=[2*inch, 4*inch])
        risk_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(risk_table)
        elements.append(Paragraph("<b>Table Context:</b> Quantitative assessment of environmental and structural hazards. The Contamination Index reflects the presence of non-cargo residues or chemical stains within the interior surfaces.", self.styles['TableNote']))
        
        # --- SECTION 3: DETAILED ANALYSIS ---
        frames = inspection_data.get('frames', [])
        if frames:
            elements.append(PageBreak())
            elements.append(Paragraph("TECHNICAL ANALYSIS LOG", self.styles['SectionHeader']))
            
            for idx, frame in enumerate(frames, 1):
                elements.append(Paragraph(f"<b>Visual Acquisition #{idx}</b>", self.styles['InfoText']))
                image_path = frame.get('overlay_path') or frame.get('image_path')
                if image_path:
                    # Resolve paths logic...
                    full_image_path = Path(image_path) # Simplified for brevity
                    if full_image_path.exists():
                        img = Image(str(full_image_path), width=5*inch, height=3.75*inch, kind='proportional')
                        elements.append(img)
                
                det_data = [['ID', 'Classification', 'Technical Category', 'System Confidence']]
                for det_idx, det in enumerate(frame.get('detections', []), 1):
                    det_data.append([str(det_idx), det.get('label'), det.get('category'), f"{det.get('confidence', 0)*100:.1f}%"])
                
                if len(det_data) > 1:
                    dt = Table(det_data, colWidths=[0.5*inch, 2*inch, 2*inch, 1.5*inch])
                    dt.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f1f1f')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
                        ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ]))
                    elements.append(dt)
                    elements.append(Paragraph(f"<b>Table Context:</b> Frame #{idx} automated object classification. Confident readings indicate precise geolocation of structural features or potential material defects.", self.styles['TableNote']))
                
                if idx % 2 == 0: elements.append(PageBreak())

        # --- SECTION 4: DEEP INTELLIGENCE ANNEX ---
        elements.append(PageBreak())
        elements.append(Paragraph("STRUCTURAL & MATERIAL INTEGRITY NARRATIVE", self.styles['SectionHeader']))
        
        narrative = inspection_data.get('ai_narrative', "Surface analysis indicates optimal structural health. No puncture-based light leaks or significant material fatigue detected.")
        elements.append(Paragraph(narrative, self.styles['Normal']))
        elements.append(Spacer(1, 0.3*inch))

        elements.append(Paragraph("PREVENTATIVE MAINTENANCE FORECAST", self.styles['SectionHeader']))
        pred_data = inspection_data.get('maintenance_forecast', [
            ["Component", "Integrity Level", "Technical Action", "Service Timeline"],
            ["Corner Castings", "High", "Standard Inspection", "12 Months"],
            ["Roof Panel", "Nominal", "Monitor Surface", "Q4 2026"],
            ["Floor Planks", "Moderate", "Odor Neutralization", "Immediate"]
        ])
        
        pt = Table(pred_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        pt.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f1f1f')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
        ]))
        elements.append(pt)
        elements.append(Paragraph("<b>Table Context:</b> Predictive analytics derived from vision data. The service timeline estimates optimal repair windows to prevent structural breach or de-certification.", self.styles['TableNote']))
        
        elements.append(Paragraph("End of Technical Inspection & Analysis Report", self.styles['CenteredFooter']))
        
        doc.build(elements, onFirstPage=self._add_footer, onLaterPages=self._add_footer)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        if output_path: output_path.write_bytes(pdf_bytes)
        return pdf_bytes