"""
PDF Report Generation Service
Generates professional inspection reports with branding, images, and structured data.
"""
from io import BytesIO
from pathlib import Path
from typing import Dict, List, Optional
import io

from PIL import Image
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RImage, PageBreak
from reportlab.platypus.flowables import HRFlowable, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime

from app.config import settings
from app.services.gemini_review_service import GeminiReviewService
from app.utils.logger import get_logger

logger = get_logger(__name__)

class ReportService:
    """Service for generating technical container inspection reports"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        self._gemini_service = GeminiReviewService()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f1f1f'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.HexColor('#6b7280'),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1f1f1f'),
            spaceAfter=12,
            spaceBefore=20,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='InfoText',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#374151'),
            spaceAfter=6,
            fontName='Helvetica'
        ))

        self.styles.add(ParagraphStyle(
            name='TableNote',
            parent=self.styles['Italic'],
            fontSize=9,
            textColor=colors.HexColor('#4b5563'),
            leftIndent=10,
            rightIndent=10,
            spaceBefore=4,
            spaceAfter=12
        ))

        self.styles.add(ParagraphStyle(
            name='CenteredFooter',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#6b7280'),
            alignment=TA_CENTER,
            fontName='Helvetica-Oblique',
            spaceBefore=30
        ))
    
    def _add_header(self, elements: List, logo_path: Optional[Path] = None):
        if logo_path and logo_path.exists():
            try:
                logo = RImage(str(logo_path), width=1.5*inch, height=1.5*inch, kind='proportional')
                logo.hAlign = 'CENTER'
                elements.append(logo)
                elements.append(Spacer(1, 0.2*inch))
            except Exception: pass
        
        elements.append(Paragraph("MCS Robotics", self.styles['CustomTitle']))
        elements.append(Paragraph("Container Inspection System", self.styles['CustomSubtitle']))
        elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#e5e7eb')))
        elements.append(Spacer(1, 0.3*inch))
    
    def _add_footer(self, canvas, doc):
        canvas.saveState()
        footer_text = f"Generated by MCS Robotics Inspection Suite v{getattr(settings, 'APP_VERSION', '3.0.0')}"
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#9ca3af'))
        canvas.drawCentredString(letter[0]/2, 0.5*inch, footer_text)
        canvas.drawRightString(letter[0] - 0.75*inch, 0.5*inch, f"Page {doc.page}")
        canvas.drawString(0.75*inch, 0.5*inch, f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        canvas.restoreState()

    def _resolve_image_full_path(self, relative_path: Optional[str]) -> Optional[Path]:
        if not relative_path:
            return None
        candidate = settings.STORAGE_ROOT / relative_path
        if candidate.exists():
            return candidate
        alt = settings.ROOT_DIR / relative_path
        if alt.exists():
            return alt
        fallback = Path(relative_path)
        if fallback.exists():
            return fallback
        return None

    def _prepare_detection_image_bytes(self, frame: Dict, detection: Dict) -> Optional[bytes]:
        image_candidates = [
            detection.get('thumbnail_path'),
            frame.get('overlay_path'),
            frame.get('image_path')
        ]

        for candidate in image_candidates:
            if not candidate:
                continue
            image_path = self._resolve_image_full_path(candidate)
            if not image_path:
                continue

            try:
                with Image.open(image_path) as raw_img:
                    raw_img = raw_img.convert('RGB')
                    clipped = self._crop_detection_bbox(raw_img, detection)
                    clipped.thumbnail((1024, 1024))
                    buffer = BytesIO()
                    clipped.save(buffer, format='JPEG', quality=75)
                    return buffer.getvalue()
            except Exception as exc:
                logger.debug(f'Could not prepare defect image {image_path}: {exc}')

        return None

    def _crop_detection_bbox(self, image_obj: Image.Image, detection: Dict) -> Image.Image:
        bbox = (
            detection.get('bbox_x'),
            detection.get('bbox_y'),
            detection.get('bbox_w'),
            detection.get('bbox_h')
        )
        if all(val is not None for val in bbox):
            x, y, w, h = bbox
            x = max(0, int(x))
            y = max(0, int(y))
            w = max(0, int(w))
            h = max(0, int(h))
            x2 = min(image_obj.width, x + w)
            y2 = min(image_obj.height, y + h)
            if x2 > x and y2 > y:
                return image_obj.crop((x, y, x2, y2))
        return image_obj

    def _get_detection_review_text(self, frame: Dict, detection: Dict, det_index: int) -> str:
        if not self._gemini_service.enabled:
            return "Descriptive analysis not available (API key missing)."

        image_bytes = self._prepare_detection_image_bytes(frame, detection)
        if not image_bytes:
            return "Descriptive analysis not available (image unavailable)."

        label = detection.get('label') or 'defect'
        confidence = detection.get('confidence')
        confidence_text = f"{confidence*100:.1f}%" if confidence is not None else "N/A"

        prompt = (
            f"Model predicted '{label}' with {confidence_text} confidence for this defect. "
            "Summarize what you see, say whether the prediction seems correct, and highlight anything alarming."
        )
        frame_key = frame.get('id') or 'frame'
        detection_key = detection.get('id') or det_index
        cache_key = f"{frame_key}_{detection_key}_{det_index}"

        review = self._gemini_service.review_image(
            image_bytes=image_bytes,
            prompt_context=prompt,
            cache_key=cache_key
        )

        return review or "Descriptive analysis unavailable at this time."

    def generate_inspection_report(self, inspection_data: Dict, output_path: Optional[Path] = None) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.75*inch, leftMargin=0.75*inch, topMargin=1*inch, bottomMargin=1*inch)
        elements = []
        
        logo_path = getattr(settings, 'ROOT_DIR', Path('.')) / "frontend" / "assets" / "images" / "pti-logo.png"
        self._add_header(elements, logo_path)
        
        elements.append(Paragraph("INSPECTION REPORT", self.styles['CustomTitle']))
        elements.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%B %d, %Y')}", self.styles['InfoText']))
        elements.append(Spacer(1, 0.3*inch))
        
        # --- SECTION 1: INSPECTION SUMMARY ---
        elements.append(Paragraph("INSPECTION SUMMARY", self.styles['SectionHeader']))
        summary_data = [
            ['Inspection ID:', str(inspection_data.get('id', 'N/A'))],
            ['Container ID:', inspection_data.get('container_id', 'UNKNOWN')],
            ['ISO Type:', inspection_data.get('iso_type', 'Unknown')],
            ['Stage:', inspection_data.get('stage', 'None')],
            ['Operational Status:', inspection_data.get('status', 'N/A').upper()],
        ]
        summary_table = Table(summary_data, colWidths=[2*inch, 4*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(summary_table)
        elements.append(Paragraph("<b>Table Context:</b> This section details administrative metadata and current logistics staging. Operational status indicates the container's readiness for transit based on structural visual confirmation.", self.styles['TableNote']))
        elements.append(Spacer(1, 0.2*inch))
        
        # --- SECTION 2: RISK ASSESSMENT ---
        elements.append(Paragraph("RISK ASSESSMENT", self.styles['SectionHeader']))
        risk_data = [
            ['Risk Score:', str(inspection_data.get('risk_score', 0))],
            ['Contamination Index:', f"{inspection_data.get('contamination_index', 1)}/9"],
            ['Safety Anomalies:', 'Yes' if inspection_data.get('anomalies_present') else 'No'],
        ]
        risk_table = Table(risk_data, colWidths=[2*inch, 4*inch])
        risk_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(risk_table)
        elements.append(Paragraph("<b>Table Context:</b> Quantitative assessment of environmental and structural hazards. The Contamination Index reflects the presence of non-cargo residues or chemical stains within the interior surfaces.", self.styles['TableNote']))
        
        # --- SECTION 3: DETAILED ANALYSIS ---
        frames = inspection_data.get('frames', [])
        print(f"Report generation: {len(frames)} frames found")  # Debug
        if frames:
            elements.append(PageBreak())
            elements.append(Paragraph("TECHNICAL ANALYSIS LOG", self.styles['SectionHeader']))
            
            for idx, frame in enumerate(frames, 1):
                elements.append(Paragraph(f"<b>Visual Acquisition #{idx}</b>", self.styles['InfoText']))
                
                # Try to display the overlay image
                image_path = frame.get('overlay_path') or frame.get('image_path')
                if image_path:
                    # Resolve absolute path using STORAGE_ROOT (where images are stored)
                    # Assume image_path is relative to STORAGE_ROOT
                    full_image_path = settings.STORAGE_ROOT / image_path
                    if not full_image_path.exists():
                        # Fallback: try relative to project root
                        full_image_path = settings.ROOT_DIR / image_path
                    if full_image_path.exists():
                        img = RImage(str(full_image_path), width=5*inch, height=3.75*inch, kind='proportional')
                        elements.append(img)
                    else:
                        elements.append(Paragraph("<i>Image not available</i>", self.styles['InfoText']))
                else:
                    elements.append(Paragraph("<i>No image available for this frame</i>", self.styles['InfoText']))
                
                # Detections table
                detections = frame.get('detections', [])
                if detections:
                    det_data = [['ID', 'Classification', 'Technical Category', 'System Confidence']]
                    for det_idx, det in enumerate(detections, 1):
                        det_data.append([
                            str(det_idx),
                            det.get('label', 'Unknown'),
                            det.get('category', 'N/A'),
                            f"{det.get('confidence', 0)*100:.1f}%"
                        ])
                    
                    dt = Table(det_data, colWidths=[0.5*inch, 2*inch, 2*inch, 1.5*inch])
                    dt.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f1f1f')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
                        ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ]))
                    elements.append(dt)
                    elements.append(Paragraph(f"<b>Table Context:</b> Frame #{idx} automated object classification. Confident readings indicate precise geolocation of structural features or potential material defects.", self.styles['TableNote']))
                    
                    if self._gemini_service.enabled:
                        elements.append(Paragraph("Descriptive narrative for each detected defect:", self.styles['InfoText']))
                        for det_idx, det in enumerate(detections, 1):
                            review_text = self._get_detection_review_text(frame, det, det_idx)
                            label = det.get('label', 'Unknown')
                            elements.append(Paragraph(f"<b>Defect #{det_idx} ({label})</b>", self.styles['InfoText']))
                            elements.append(Paragraph(review_text, self.styles['InfoText']))
                            elements.append(Spacer(1, 0.08*inch))
                    else:
                        elements.append(Paragraph("Descriptive analysis unavailable; please check configuration.", self.styles['InfoText']))
                else:
                    elements.append(Paragraph("<i>No detections in this frame</i>", self.styles['InfoText']))
                
                # Add a page break every 2 frames (optional)
                if idx % 2 == 0 and idx < len(frames):
                    elements.append(PageBreak())
                else:
                    elements.append(Spacer(1, 0.2*inch))

        # --- SECTION 4: DEEP INTELLIGENCE ANNEX ---
        elements.append(PageBreak())
        elements.append(Paragraph("STRUCTURAL & MATERIAL INTEGRITY NARRATIVE", self.styles['SectionHeader']))
        
        narrative = inspection_data.get('ai_narrative', "Surface analysis indicates optimal structural health. No puncture-based light leaks or significant material fatigue detected.")
        elements.append(Paragraph(narrative, self.styles['Normal']))
        elements.append(Spacer(1, 0.3*inch))

        elements.append(Paragraph("PREVENTATIVE MAINTENANCE FORECAST", self.styles['SectionHeader']))
        
        # Generate dynamic maintenance forecast from detections
        maintenance_data = [["Component", "Issue Detected", "Technical Action", "Service Timeline"]]
        
        # Aggregate unique issues from all frames
        unique_detections = {}
        for frame in frames:
            for det in frame.get('detections', []):
                label = det.get('label', 'Unknown')
                if label not in unique_detections:
                    unique_detections[label] = det
        
        if unique_detections:
            for label, det in unique_detections.items():
                component = "Panel/Structure"
                action = "Inspect and Monitor"
                timeline = "Standard Cycle"
                
                label_lower = label.lower()
                if "floor" in label_lower:
                    component = "Floor Planks"
                elif "corner" in label_lower:
                    component = "Corner Castings"
                elif "roof" in label_lower:
                    component = "Roof Panel"
                elif "door" in label_lower:
                    component = "Door Hardware"
                
                if "rust" in label_lower or "corrosion" in label_lower:
                    action = "Surface Treatment"
                    timeline = "Q2 2026"
                elif "hole" in label_lower or "crack" in label_lower:
                    action = "Structural Patch"
                    timeline = "Immediate"
                elif "dust" in label_lower or "powder" in label_lower or "oil" in label_lower or "stain" in label_lower:
                    action = "Cleaning/Sanitization"
                    timeline = "Before Loading"
                elif "dent" in label_lower:
                    action = "Cold Straightening"
                    timeline = "Next Depot"
                
                maintenance_data.append([component, label, action, timeline])
        else:
            # Fallback if no issues found
            maintenance_data.append(["Structure", "None Detected", "Visual Confirmation", "Next Cycle"])
            maintenance_data.append(["Interior", "Clean", "Odor Check", "Routine"])
        
        pt = Table(maintenance_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        pt.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f1f1f')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
        ]))
        elements.append(pt)
        elements.append(Paragraph("<b>Table Context:</b> Predictive analytics derived from vision data. The service timeline estimates optimal repair windows to prevent structural breach or de-certification.", self.styles['TableNote']))
        
        elements.append(Paragraph("End of Technical Inspection & Analysis Report", self.styles['CenteredFooter']))
        
        doc.build(elements, onFirstPage=self._add_footer, onLaterPages=self._add_footer)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        if output_path: output_path.write_bytes(pdf_bytes)
        return pdf_bytes
